spring.application.name=EXTRA_EstudiantesMVC

server.port=8081

spring.datasource.url=jdbc:h2:mem:estudiantes
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Espera a que Hibernate cree las tablas, y solo después ejecuta los scripts SQL
spring.jpa.defer-datasource-initialization=true

