spring.application.name=EXTRA_EstudiantesMVC

server.port=8081

spring.datasource.url=jdbc:h2:mem:estudiantes
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Espera a que Hibernate cree las tablas, y solo después ejecuta los scripts SQL
spring.jpa.defer-datasource-initialization=true

# LOGGER

# nivel global (root)
logging.level.root=INFO

# nivel por paquete o clase (ejemplo para tu app)
logging.level.es.daw.extra_estudiantesmvc=TRACE
#logging.level.es.daw.extra_estudiantesmvc.service=DEBUG

# escribir también a fichero (Spring Boot)
logging.file.name=app.log         # crea app.log en working dir
# o para una ruta
#logging.file.path=logs

# cambiar patrón de consola (opcional)
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n


